# Generated by Django 6.0.3 on 2026-08-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('recipient_name', models.CharField(max_length=150)),
                ('program_name', models.CharField(max_length=200)),
                ('college_name', models.CharField(default='Springfield College', max_length=150)),
                ('dean_name', models.CharField(default='Dr. Emily Carter', max_length=150)),
                ('registrar_name', models.CharField(default='Dr. Michael Reyes', max_length=150)),
                ('issue_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
